In [2]:
import pandas as pd

In [4]:
iphone_df = pd.read_csv('./data/iphone.csv', index_col = 0)
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [5]:
iphone_df.loc['iPhone 8','메모리']

'2GB'

### 만약 새로운 값을 넣고 싶으면 할당 연산자로 새로운 값을 넣어주면됨.

두 가지 조회방법    
첫째. loc[]    
둘째. iloc[]

In [16]:
iphone_df.loc['iPhone 8','메모리'] = '2.5GB'
# 첫번쨰는 해당 로우, 두번쨰는 컬럼으로 두게 되면 해당 셀의 값 한개 값이 
# 나온다. 
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [17]:
iphone_df.iloc[1,2] = '32.5GB'
iphone_df

                      출시일  디스플레이     메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5     3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  32.5GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5     3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8     3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8     4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5     4GB  iOS 12.0     Yes

In [19]:
# iPhone 8의 출시 버전을 바꾸어 봅시다. 
iphone_df.iloc[1,3] = 'iOS 10.3'
iphone_df

                      출시일  디스플레이     메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5     3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  32.5GB  iOS 10.3      No
iPhone 8 Plus  2017-09-22    5.5     3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8     3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8     4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5     4GB  iOS 12.0     Yes

## row 하나를 통으로 바꾸고 싶은 경우라면?

Step1. 우선 한 줄을 선택한다.

In [21]:
iphone_df.loc['iPhone 8']

출시일        2017-09-22
디스플레이             4.7
메모리            32.5GB
출시 버전        iOS 10.3
Face ID            No
Name: iPhone 8, dtype: object

### 리스트로 개수에 맞게 값들을 다 바꿔 버린다.

In [23]:
iphone_df.loc['iPhone 8'] = [None, None,None,None,None]
iphone_df

                      출시일  디스플레이   메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5   3GB  iOS 10.0      No
iPhone 8             None    NaN  None      None    None
iPhone 8 Plus  2017-09-22    5.5   3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8   3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8   4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5   4GB  iOS 12.0     Yes

# column 하나를 통으로 바꾸고 싶은 경우라면

In [29]:
# 컬럼 하나만을 선택하는 방법 기본형으로 수정하는 방법 
iphone_df.loc[:,'디스플레이']  =['4.7 in','5.5 in','4.7 in','5.5 in','5.8 in','6.5 in']
iphone_df.loc[:,'디스플레이']

iPhone 7 Plus    4.7 in
iPhone 8         5.5 in
iPhone 8 Plus    4.7 in
iPhone X         5.5 in
iPhone XS        5.8 in
iPhone XS Max    6.5 in
Name: 디스플레이, dtype: object

In [36]:
# 또는 그냥 컬럼 이름만 넣어도 된다. 단축형으로 하는 방법 
iphone_df['출시일'] = ['?','?','?','?','?','?']
iphone_df

              출시일   디스플레이   메모리     출시 버전 Face ID
iPhone 7 Plus   ?  4.7 in   3GB  iOS 10.0      No
iPhone 8        ?  5.5 in  None      None    None
iPhone 8 Plus   ?  4.7 in   3GB  iOS 11.0      No
iPhone X        ?  5.5 in   3GB  iOS 11.1     Yes
iPhone XS       ?  5.8 in   4GB  iOS 12.0     Yes
iPhone XS Max   ?  6.5 in   4GB  iOS 12.0     Yes

In [40]:
iphone_df.iloc[:,0] = ['4.7 in','5.5 in',
 '4.7 in',
        '5.5 in',
        '5.8 in',
   '6.5 in']

len(iphone_df)

6

In [50]:
# Face ID 칼럼을 모두 No로 바꿉시다. 
iphone_df['Face ID'] = ['NO' if i>= 0 else 'YES' for i in range(len(iphone_df)) ] # len()을 써서 모든 Face ID 모든(len(iphone_df)) 개수만큼 바꾼거임. 
iphone_df
iphone_df['출시일'] = [None for i in range(len(iphone_df)) if i >= 0]
iphone_df

                출시일   디스플레이   메모리     출시 버전 Face ID
iPhone 7 Plus  None  4.7 in   3GB  iOS 10.0      NO
iPhone 8       None  5.5 in  None      None      NO
iPhone 8 Plus  None  4.7 in   3GB  iOS 11.0      NO
iPhone X       None  5.5 in   3GB  iOS 11.1      NO
iPhone XS      None  5.8 in   4GB  iOS 12.0      NO
iPhone XS Max  None  6.5 in   4GB  iOS 12.0      NO

In [52]:
# 걍 문자열 하나만 넣으면 일괄적으로 다 처리함. 
iphone_df['Face ID'] = 'YES'
iphone_df

                출시일   디스플레이   메모리     출시 버전 Face ID
iPhone 7 Plus  None  4.7 in   3GB  iOS 10.0     YES
iPhone 8       None  5.5 in  None      None     YES
iPhone 8 Plus  None  4.7 in   3GB  iOS 11.0     YES
iPhone X       None  5.5 in   3GB  iOS 11.1     YES
iPhone XS      None  5.8 in   4GB  iOS 12.0     YES
iPhone XS Max  None  6.5 in   4GB  iOS 12.0     YES

In [56]:
iphone_df['디스플레이'] = [i+0.1 for i in range(len(iphone_df))]
iphone_df

                출시일  디스플레이   메모리     출시 버전 Face ID
iPhone 7 Plus  None    0.1   3GB  iOS 10.0     YES
iPhone 8       None    1.1  None      None     YES
iPhone 8 Plus  None    2.1   3GB  iOS 11.0     YES
iPhone X       None    3.1   3GB  iOS 11.1     YES
iPhone XS      None    4.1   4GB  iOS 12.0     YES
iPhone XS Max  None    5.1   4GB  iOS 12.0     YES

In [62]:
iphone_df['Face ID'] = 'NO'
iphone_df

                출시일  디스플레이   메모리     출시 버전 Face ID
iPhone 7 Plus  None    0.1   3GB  iOS 10.0      NO
iPhone 8       None    1.1  None      None      NO
iPhone 8 Plus  None    2.1   3GB  iOS 11.0      NO
iPhone X       None    3.1   3GB  iOS 11.1      NO
iPhone XS      None    4.1   4GB  iOS 12.0      NO
iPhone XS Max  None    5.1   4GB  iOS 12.0      NO

In [61]:
iphone_df['디스플레이'].value_counts() > 1.0

0.1    False
4.1    False
5.1    False
2.1    False
1.1    False
3.1    False
Name: 디스플레이, dtype: bool